Upped version of Perl Gwybodaeth depends on to 5.8
This will hopefully stem cpantester FAILS on 5.6.2:
 Error:  Unknown discipline ':utf8'

See:
http://www.nntp.perl.org/group/perl.cpan.testers/2009/09/msg5345085.html
http://www.nntp.perl.org/group/perl.cpan.testers/2009/09/msg5322363.html

	modified:   Build.PL